version: '3'


services:
    app:
        image: docker.pkg.github.com/scratchmex/covidwithtech/covidwithtech_app
        build: .
        command: gunicorn -b 0.0.0.0 app:app
        environment:
            DOMAIN: ${APP_DOMAIN}
            NEWS_API_KEY: ${NEWS_API_KEY}
        networks:
            - default
            - traefik
        deploy:
            labels:
            - "traefik.enable=true"
            - "traefik.http.routers.covidwithtech_app.entrypoints=websecure"
            - "traefik.http.routers.covidwithtech_app.tls=true"
            - "traefik.http.routers.covidwithtech_app.tls.certresolver=httpresolver"
            - "traefik.http.routers.covidwithtech_app.rule=Host(`${APP_DOMAIN}`)"
            - "traefik.http.services.covidwithtech_app.loadbalancer.server.port=8000"

networks:
    traefik:
        external: true
